apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: planmyjourney
  namespace: argocd
spec:
  description: Plan My Journey dev and prod environments
  sourceRepos:
    - https://github.com/Plan-My-Journey/PlanMyJourney-Gitops
    - https://github.com/envoyproxy/gateway
    - https://prometheus-community.github.io/helm-charts
    - https://charts.jetstack.io
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: envoy-gateway-system
      server: https://kubernetes.default.svc
    - namespace: prod
      server: https://kubernetes.default.svc
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: gateway-system
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
