apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kgateway
  namespace: gateway-system
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  description: KGateway controller for Plan My Journey API Gateway
