apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 01-gateway-parameters-nlb.yaml
  - 02-gateway.yaml
  - 03-gateway-pdb.yaml
  - routes/prod-routes.yaml
  - routes/dev-routes.yaml
