replicaCount: 2

resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "2000m"
    memory: "2Gi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

podDisruptionBudget:
  enabled: true
  minAvailable: 1

configMap:
  enabled: true
  data:
    BEDROCK_MODEL_ID: "amazon.nova-pro-v1:0"
    BEDROCK_REGION: "us-east-1"
    LOG_LEVEL: "warning"
    ENVIRONMENT: "production"
    AWS_REGION: "us-east-1"
    SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/235270183260/ai-travel-prod-ai-jobs"
    JOBS_TABLE_NAME: "ai-travel-prod-ai-jobs"
    ASYNC_JOBS_ENABLED: "false"

image:
  tag: "v1.0.1"
