apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ai-worker
  namespace: argocd
  labels:
    environment: dev
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: planmyjourney
  source:
    repoURL: https://github.com/Plan-My-Journey/PlanMyJourney-Gitops
    targetRevision: main
    path: helm-charts/ai-worker
    helm:
      releaseName: ai-worker
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
