apiVersion: v1
kind: ConfigMap
metadata:
  name: cognito-config
  namespace: production
data:
  COGNITO_REGION: "us-east-1"
  COGNITO_REDIRECT_URI: "https://invest-iq.online/callback"
  COGNITO_LOGOUT_URI: "https://invest-iq.online/"
  COGNITO_SCOPES: "openid email profile"
