apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: user-service-config
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: production
      - op: replace
        path: /data/CORS_ORIGINS
        value: "https://invest-iq.online,https://www.invest-iq.online,https://api.invest-iq.online"
