replicaCount: 1

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: false

configMap:
  enabled: true
  data:
    ENVIRONMENT: "dev"

ingress:
  enabled: false

image:
  tag: "e1c962d6e622091c5fcb7a050caeb5e88c8b9ee6"
