replicaCount: 2
resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70
podDisruptionBudget:
  enabled: false
configMap:
  enabled: true
  data:
    ENVIRONMENT: "dev"
ingress:
  enabled: false
image:
  tag: "7e9951293b123ec9882029f9ca13b6d04846ced6"
