apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: travel-service-pdb
  namespace: production
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: travel-service
