apiVersion: v1
kind: Service
metadata:
  name: travel-service
  namespace: production
  labels:
    app.kubernetes.io/name: travel-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app.kubernetes.io/name: travel-service
