apiVersion: v1
kind: ServiceAccount
metadata:
  name: travel-service
  namespace: production
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::235270183260:role/ai-travel-travel-service-prod
automountServiceAccountToken: false
