configMap:
  data:
    ENVIRONMENT: "dev"
    SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/235270183260/ai-travel-prod-ai-jobs"
    JOBS_TABLE_NAME: "ai-travel-prod-ai-jobs"
keda:
  maxReplicaCount: 5
  queueLength: "5"
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::235270183260:role/ai-travel-ai-worker-prod"
image:
  tag: "8866f58060df43001b1f86dbfc06fa3cd5a786d1"
