configMap:
  data:
    ENVIRONMENT: "dev"
    SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/235270183260/ai-travel-prod-ai-jobs"
    JOBS_TABLE_NAME: "ai-travel-prod-ai-jobs"

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::235270183260:role/ai-travel-ai-worker-prod"

image:
  tag: "b98bcc6e0021dfca03aa891e8a9fa58661bdfe93"
