apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - rbac.yaml
  - networkpolicy.yaml
  - pdb.yaml
  - hpa.yaml
  - cognito/configmap.yaml
  - cognito/secret.yaml
  - services/ai-service/serviceaccount.yaml
  - services/ai-service/configmap.yaml
  - services/ai-service/deployment.yaml
  - services/ai-service/service.yaml
  - services/ai-service/hpa.yaml
  - services/ai-service/pdb.yaml
  - services/travel-service/serviceaccount.yaml
  - services/travel-service/configmap.yaml
  - services/travel-service/deployment.yaml
  - services/travel-service/service.yaml
  - services/travel-service/hpa.yaml
  - services/travel-service/pdb.yaml
  - services/utility-service/serviceaccount.yaml
  - services/utility-service/configmap.yaml
  - services/utility-service/deployment.yaml
  - services/utility-service/service.yaml
  - services/utility-service/hpa.yaml
  - services/utility-service/pdb.yaml
  - ../../gateway/04-http-routes.yaml

commonLabels:
  app.kubernetes.io/part-of: planmyjourney
  app.kubernetes.io/managed-by: flux
