apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: user-service-config
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: dev
      - op: replace
        path: /data/CORS_ORIGINS
        value: "https://dev.invest-iq.online,http://localhost:5173"
  - target:
      kind: Deployment
      name: user-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
